### PR TITLE
fix use of snakewords

### PR DESCRIPTION
**Pull request by dougma**
Hello. I hit this bug when attempting to generate some ruby!

### CODE REVIEW

**Comment by cjheath** [comment]
Thank you! But please consider using the new Ruby generator from activefacts-compositions:

```
schema_compositor --binary --ruby <file>.cql
```

Clifford Heath.

**Comment by cjheath** [comment]
Also, can I have the CQL or ORM you used to trigger this problem? The fix doesn't fail any of my test cases (in activefacts-examples) so I need a new test case.

**Comment by cjheath** [comment]
It's ok, I have a test case. You used a role name on a unary fact type. I don't think I ever did that with the old generator, though there are some cases of it that I use with the new one. Generally with a unary fact type, you get a good role name from the reading. E.g. "Thing is broken" results in Thing having the role name "is_broken". Role names on unaries look odd in CQL anyhow: "Thing (as Broken Thing) is broken"...  which tends to lead to role names that don't actually reflect their meaning.

**Comment by cjheath** [comment]
Also: The SQL and Rails generators in schema_compositor are much better than the old ones...

**Comment by dougma** [comment]
Indeed i did have a named unary fact type; not actually intentionally (this was my first ORM model)! Thanks for the pointer to activefacts-compositions.

**Pull request merged**
